/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;

import android.os.Parcel;
import android.os.Parcelable;

public class Comment implements Parcelable {

  private From from;


  private String id;


  private String created_time;


  private String text;
  public String getCreated_time() {
    return created_time;
  }
  public From getFrom() {
    return from;
  }
  public String getId() {
    return id;
  }
  public String getText() {
    return text;
  }

  @Override
  public int describeContents() {
    return 0;
  }

  public Comment() {}

  Comment(Parcel in) {
    this.from = in.readParcelable(this.getClass().getClassLoader());
    this.id = in.readString();
    this.created_time = in.readString();
    this.text = in.readString();
  }

  @Override
  public void writeToParcel(Parcel parcel, int i) {
    parcel.writeParcelable(from, i);
    parcel.writeString(id);
    parcel.writeString(created_time);
    parcel.writeString(text);
  }

  /**
  * Builder for Datum
  **/
  public static class DatumBuilder {
    private Comment toBuild = new Comment();

    public DatumBuilder() {
    }

    public Comment build() {
      return toBuild;
    }

    public DatumBuilder created_time(String value) {
      toBuild.created_time = value;
      return this;
    }
    public DatumBuilder from(From value) {
      toBuild.from = value;
      return this;
    }
    public DatumBuilder id(String value) {
      toBuild.id = value;
      return this;
    }
    public DatumBuilder text(String value) {
      toBuild.text = value;
      return this;
    }
  }
}
