/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "low_resolution" : {
    "url" : "https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-15/s306x306/e15/11244623_1617956361773883_1448620956_n.jpg",
    "width" : 306,
    "height" : 306
  },
  "thumbnail" : {
    "url" : "https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-15/s150x150/e15/11244623_1617956361773883_1448620956_n.jpg",
    "width" : 150,
    "height" : 150
  },
  "standard_resolution" : {
    "url" : "https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-15/e15/11244623_1617956361773883_1448620956_n.jpg",
    "width" : 640,
    "height" : 640
  }
}

 */

public class Images {

  
  private Low_resolution low_resolution;

  
  private Standard_resolution standard_resolution;

  
  private Thumbnail thumbnail;

  public Low_resolution getLow_resolution() {
    return low_resolution;
  }
  public Standard_resolution getStandard_resolution() {
    return standard_resolution;
  }
  public Thumbnail getThumbnail() {
    return thumbnail;
  }

  /**
  * Builder for Images
  **/
  public static class ImagesBuilder {
    private Images toBuild = new Images();

    public ImagesBuilder() {
    }

    public Images build() {
      return toBuild;
    }

    public ImagesBuilder low_resolution(Low_resolution value) {
      toBuild.low_resolution = value;
      return this;
    }
    public ImagesBuilder standard_resolution(Standard_resolution value) {
      toBuild.standard_resolution = value;
      return this;
    }
    public ImagesBuilder thumbnail(Thumbnail value) {
      toBuild.thumbnail = value;
      return this;
    }
  }
}
