/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "username" : "diegoroyot",
  "profile_picture" : "https://instagramimages-a.akamaihd.net/profiles/anonymousUser.jpg",
  "id" : "2137656897",
  "full_name" : "DIEGO"
}

 */

public class LikesDatum {

  
  private String full_name;

  
  private String id;

  
  private String profile_picture;

  
  private String username;

  public String getFull_name() {
    return full_name;
  }
  public String getId() {
    return id;
  }
  public String getProfile_picture() {
    return profile_picture;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for LikesDatum
  **/
  public static class LikesDatumBuilder {
    private LikesDatum toBuild = new LikesDatum();

    public LikesDatumBuilder() {
    }

    public LikesDatum build() {
      return toBuild;
    }

    public LikesDatumBuilder full_name(String value) {
      toBuild.full_name = value;
      return this;
    }
    public LikesDatumBuilder id(String value) {
      toBuild.id = value;
      return this;
    }
    public LikesDatumBuilder profile_picture(String value) {
      toBuild.profile_picture = value;
      return this;
    }
    public LikesDatumBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
