/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "url" : "https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-15/s306x306/e15/11244623_1617956361773883_1448620956_n.jpg",
  "width" : 306,
  "height" : 306
}

 */

public class Low_resolution {

  
  private Integer height;

  
  private String url;

  
  private Integer width;

  public Integer getHeight() {
    return height;
  }
  public String getUrl() {
    return url;
  }
  public Integer getWidth() {
    return width;
  }

  /**
  * Builder for Low_resolution
  **/
  public static class Low_resolutionBuilder {
    private Low_resolution toBuild = new Low_resolution();

    public Low_resolutionBuilder() {
    }

    public Low_resolution build() {
      return toBuild;
    }

    public Low_resolutionBuilder height(Integer value) {
      toBuild.height = value;
      return this;
    }
    public Low_resolutionBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
    public Low_resolutionBuilder width(Integer value) {
      toBuild.width = value;
      return this;
    }
  }
}
