/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "code" : 200
}

 */

public class Meta {

  
  private Integer code;

  public Integer getCode() {
    return code;
  }

  /**
  * Builder for Meta
  **/
  public static class MetaBuilder {
    private Meta toBuild = new Meta();

    public MetaBuilder() {
    }

    public Meta build() {
      return toBuild;
    }

    public MetaBuilder code(Integer value) {
      toBuild.code = value;
      return this;
    }
  }
}
