/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "meta" : {
    "code" : 200
  },
  "data" : [ {
    "tags" : [ ],
    "comments" : {
      "count" : 184,
      "data" : [ {
        "created_time" : "1431150745",
        "text" : "@rdiaz891",
        "from" : {
          "username" : "mdiaz103",
          "profile_picture" : "https://instagramimages-a.akamaihd.net/profiles/profile_194206121_75sq_1378970369.jpg",
          "id" : "194206121",
          "full_name" : ""
        },
        "id" : "980886008683966590"
      }, {
        "created_time" : "1431151463",
          ...

 */

public class PopularMediasResult {

  
  private List<Photo> data;

  
  private Meta meta;

  public List<Photo> getData() {
    return data;
  }
  public Meta getMeta() {
    return meta;
  }

  /**
  * Builder for PopularMediasResult
  **/
  public static class PopularMediasResultBuilder {
    private PopularMediasResult toBuild = new PopularMediasResult();

    public PopularMediasResultBuilder() {
    }

    public PopularMediasResult build() {
      return toBuild;
    }

    public PopularMediasResultBuilder data(List<Photo> value) {
      toBuild.data = value;
      return this;
    }
    public PopularMediasResultBuilder meta(Meta value) {
      toBuild.meta = value;
      return this;
    }
  }
}
