/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "y" : 0.8125,
  "x" : 0.48125
}

 */

public class Position {

  
  private Double x;

  
  private Double y;

  public Double getX() {
    return x;
  }
  public Double getY() {
    return y;
  }

  /**
  * Builder for Position
  **/
  public static class PositionBuilder {
    private Position toBuild = new Position();

    public PositionBuilder() {
    }

    public Position build() {
      return toBuild;
    }

    public PositionBuilder x(Double value) {
      toBuild.x = value;
      return this;
    }
    public PositionBuilder y(Double value) {
      toBuild.y = value;
      return this;
    }
  }
}
