/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "username" : "nolimitbmore",
  "profile_picture" : "https://igcdn-photos-c-a.akamaihd.net/hphotos-ak-xap1/t51.2885-19/10817874_721321337963874_285079410_a.jpg",
  "id" : "179298824",
  "full_name" : "410-426-RIMS(7467)"
}

 */

public class User {

  
  private String full_name;

  
  private String id;

  
  private String profile_picture;

  
  private String username;

  public String getFull_name() {
    return full_name;
  }
  public String getId() {
    return id;
  }
  public String getProfile_picture() {
    return profile_picture;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for User
  **/
  public static class UserBuilder {
    private User toBuild = new User();

    public UserBuilder() {
    }

    public User build() {
      return toBuild;
    }

    public UserBuilder full_name(String value) {
      toBuild.full_name = value;
      return this;
    }
    public UserBuilder id(String value) {
      toBuild.id = value;
      return this;
    }
    public UserBuilder profile_picture(String value) {
      toBuild.profile_picture = value;
      return this;
    }
    public UserBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
