/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api;


import com.jim.instagramclientandroid.api.model.beans.*;

import retrofit.Callback;
import retrofit.http.GET;
import retrofit.http.Query;

public interface InstagramApi {

  @GET("/media/popular")
  void getPopularMedias(@Query("client_id") String client_id, Callback<PopularMediasResult> cb);


}
