/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.jim.instagramclientandroid.api.model.beans.*;

public interface Instagram {

  /**
   * Generated from URL GET https://api.instagram.com/v1/media/popular?client_id=dac6dad78dae4fac9c89f1df2b094bf9
   * GET v1/media/popular
   * @param client_id  style:QUERY
   * @param listener
   * @return PopularMediasResult
   */
  Call<PopularMediasResult> getPopularMedias(
     String client_id,
     StateChangedListener listener
  );


}
