/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.jim.instagramclientandroid.api.model.beans.*;

public class InstagramFactory extends ControllerFactory<Instagram> {
  public InstagramFactory(MagnetMobileClient magnetClient) {
    super(Instagram.class, InstagramSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller Instagram
  public static class InstagramSchemaFactory extends AbstractControllerSchemaFactory {
    private static InstagramSchemaFactory __instance;

    public static synchronized InstagramSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new InstagramSchemaFactory();
      }

      return __instance;
    }

    private InstagramSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getPopularMedias
      JMethod method1 = addMethod("getPopularMedias",
        "v1/media/popular",
        "GET",
        PopularMediasResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://api.instagram.com");
      method1.addParam("client_id",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
