/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "created_time" : "1431142181",
  "text" : "FordMustang\nonacustomsetofHREwheels\n|Follow:@nolimitbmore|\nForMoreGreatBuilds",
  "from" : {
    "username" : "motor_head_",
    "profile_picture" : "https://igcdn-photos-f-a.akamaihd.net/hphotos-ak-xpf1/t51.2885-19/10561127_1514465668768589_1681274606_a.jpg",
    "id" : "28584235",
    "full_name" : "WelcomeToTheCarGame"
  },
  "id" : "980814168661832576"
}

 */

public class Caption {

  
  private String created_time;

  
  private From from;

  
  private String id;

  
  private String text;

  public String getCreated_time() {
    return created_time;
  }
  public From getFrom() {
    return from;
  }
  public String getId() {
    return id;
  }
  public String getText() {
    return text;
  }

  /**
  * Builder for Caption
  **/
  public static class CaptionBuilder {
    private Caption toBuild = new Caption();

    public CaptionBuilder() {
    }

    public Caption build() {
      return toBuild;
    }

    public CaptionBuilder created_time(String value) {
      toBuild.created_time = value;
      return this;
    }
    public CaptionBuilder from(From value) {
      toBuild.from = value;
      return this;
    }
    public CaptionBuilder id(String value) {
      toBuild.id = value;
      return this;
    }
    public CaptionBuilder text(String value) {
      toBuild.text = value;
      return this;
    }
  }
}
