/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "created_time" : "1431150745",
  "text" : "@rdiaz891",
  "from" : {
    "username" : "mdiaz103",
    "profile_picture" : "https://instagramimages-a.akamaihd.net/profiles/profile_194206121_75sq_1378970369.jpg",
    "id" : "194206121",
    "full_name" : ""
  },
  "id" : "980886008683966590"
}

 */

public class Datum {

  
  private Caption caption;

  
  private Comments comments;

  
  private String created_time;

  
  private String filter;

  
  private From from;

  
  private String id;

  
  private Images images;

  
  private Likes likes;

  
  private String link;

  
  private Location location;

  
  private List<java.lang.String> tags;

  
  private String text;

  
  private String type;

  
  private User user;

  
  private List<Users_in_photo> users_in_photo;

  
  private Videos videos;

  public Caption getCaption() {
    return caption;
  }
  public Comments getComments() {
    return comments;
  }
  public String getCreated_time() {
    return created_time;
  }
  public String getFilter() {
    return filter;
  }
  public From getFrom() {
    return from;
  }
  public String getId() {
    return id;
  }
  public Images getImages() {
    return images;
  }
  public Likes getLikes() {
    return likes;
  }
  public String getLink() {
    return link;
  }
  public Location getLocation() {
    return location;
  }
  public List<java.lang.String> getTags() {
    return tags;
  }
  public String getText() {
    return text;
  }
  public String getType() {
    return type;
  }
  public User getUser() {
    return user;
  }
  public List<Users_in_photo> getUsers_in_photo() {
    return users_in_photo;
  }
  public Videos getVideos() {
    return videos;
  }

  /**
  * Builder for Datum
  **/
  public static class DatumBuilder {
    private Datum toBuild = new Datum();

    public DatumBuilder() {
    }

    public Datum build() {
      return toBuild;
    }

    public DatumBuilder caption(Caption value) {
      toBuild.caption = value;
      return this;
    }
    public DatumBuilder comments(Comments value) {
      toBuild.comments = value;
      return this;
    }
    public DatumBuilder created_time(String value) {
      toBuild.created_time = value;
      return this;
    }
    public DatumBuilder filter(String value) {
      toBuild.filter = value;
      return this;
    }
    public DatumBuilder from(From value) {
      toBuild.from = value;
      return this;
    }
    public DatumBuilder id(String value) {
      toBuild.id = value;
      return this;
    }
    public DatumBuilder images(Images value) {
      toBuild.images = value;
      return this;
    }
    public DatumBuilder likes(Likes value) {
      toBuild.likes = value;
      return this;
    }
    public DatumBuilder link(String value) {
      toBuild.link = value;
      return this;
    }
    public DatumBuilder location(Location value) {
      toBuild.location = value;
      return this;
    }
    public DatumBuilder tags(List<java.lang.String> value) {
      toBuild.tags = value;
      return this;
    }
    public DatumBuilder text(String value) {
      toBuild.text = value;
      return this;
    }
    public DatumBuilder type(String value) {
      toBuild.type = value;
      return this;
    }
    public DatumBuilder user(User value) {
      toBuild.user = value;
      return this;
    }
    public DatumBuilder users_in_photo(List<Users_in_photo> value) {
      toBuild.users_in_photo = value;
      return this;
    }
    public DatumBuilder videos(Videos value) {
      toBuild.videos = value;
      return this;
    }
  }
}
