/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "latitude" : 43.481225,
  "longitude" : -110.761338333
}

 */

public class Location {

  
  private Integer id;

  
  private Double latitude;

  
  private Double longitude;

  
  private String name;

  public Integer getId() {
    return id;
  }
  public Double getLatitude() {
    return latitude;
  }
  public Double getLongitude() {
    return longitude;
  }
  public String getName() {
    return name;
  }

  /**
  * Builder for Location
  **/
  public static class LocationBuilder {
    private Location toBuild = new Location();

    public LocationBuilder() {
    }

    public Location build() {
      return toBuild;
    }

    public LocationBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public LocationBuilder latitude(Double value) {
      toBuild.latitude = value;
      return this;
    }
    public LocationBuilder longitude(Double value) {
      toBuild.longitude = value;
      return this;
    }
    public LocationBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
  }
}
