/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "url" : "https://scontent.cdninstagram.com/hphotos-xaf1/t50.2886-16/11235676_636913146440099_1431364268_s.mp4",
  "width" : 480,
  "height" : 480
}

 */

public class Low_bandwidth {

  
  private Integer height;

  
  private String url;

  
  private Integer width;

  public Integer getHeight() {
    return height;
  }
  public String getUrl() {
    return url;
  }
  public Integer getWidth() {
    return width;
  }

  /**
  * Builder for Low_bandwidth
  **/
  public static class Low_bandwidthBuilder {
    private Low_bandwidth toBuild = new Low_bandwidth();

    public Low_bandwidthBuilder() {
    }

    public Low_bandwidth build() {
      return toBuild;
    }

    public Low_bandwidthBuilder height(Integer value) {
      toBuild.height = value;
      return this;
    }
    public Low_bandwidthBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
    public Low_bandwidthBuilder width(Integer value) {
      toBuild.width = value;
      return this;
    }
  }
}
