/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "url" : "https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-15/e15/11244623_1617956361773883_1448620956_n.jpg",
  "width" : 640,
  "height" : 640
}

 */

public class Standard_resolution {

  
  private Integer height;

  
  private String url;

  
  private Integer width;

  public Integer getHeight() {
    return height;
  }
  public String getUrl() {
    return url;
  }
  public Integer getWidth() {
    return width;
  }

  /**
  * Builder for Standard_resolution
  **/
  public static class Standard_resolutionBuilder {
    private Standard_resolution toBuild = new Standard_resolution();

    public Standard_resolutionBuilder() {
    }

    public Standard_resolution build() {
      return toBuild;
    }

    public Standard_resolutionBuilder height(Integer value) {
      toBuild.height = value;
      return this;
    }
    public Standard_resolutionBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
    public Standard_resolutionBuilder width(Integer value) {
      toBuild.width = value;
      return this;
    }
  }
}
