/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "url" : "https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-15/s150x150/e15/11244623_1617956361773883_1448620956_n.jpg",
  "width" : 150,
  "height" : 150
}

 */

public class Thumbnail {

  
  private Integer height;

  
  private String url;

  
  private Integer width;

  public Integer getHeight() {
    return height;
  }
  public String getUrl() {
    return url;
  }
  public Integer getWidth() {
    return width;
  }

  /**
  * Builder for Thumbnail
  **/
  public static class ThumbnailBuilder {
    private Thumbnail toBuild = new Thumbnail();

    public ThumbnailBuilder() {
    }

    public Thumbnail build() {
      return toBuild;
    }

    public ThumbnailBuilder height(Integer value) {
      toBuild.height = value;
      return this;
    }
    public ThumbnailBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
    public ThumbnailBuilder width(Integer value) {
      toBuild.width = value;
      return this;
    }
  }
}
