/**
 * File generated by Magnet rest2mobile 1.1 - May 8, 2015 11:30:13 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.instagramclientandroid.api.model.beans;


/**
 * Generated from json example
{
  "position" : {
    "y" : 0.8125,
    "x" : 0.48125
  },
  "user" : {
    "username" : "nolimitbmore",
    "profile_picture" : "https://igcdn-photos-c-a.akamaihd.net/hphotos-ak-xap1/t51.2885-19/10817874_721321337963874_285079410_a.jpg",
    "id" : "179298824",
    "full_name" : "410-426-RIMS(7467)"
  }
}

 */

public class Users_in_photo {

  
  private Position position;

  
  private User user;

  public Position getPosition() {
    return position;
  }
  public User getUser() {
    return user;
  }

  /**
  * Builder for Users_in_photo
  **/
  public static class Users_in_photoBuilder {
    private Users_in_photo toBuild = new Users_in_photo();

    public Users_in_photoBuilder() {
    }

    public Users_in_photo build() {
      return toBuild;
    }

    public Users_in_photoBuilder position(Position value) {
      toBuild.position = value;
      return this;
    }
    public Users_in_photoBuilder user(User value) {
      toBuild.user = value;
      return this;
    }
  }
}
